name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install deps
        run: yarn install

  test:
    runs-on: ubuntu-latest
    needs: build-and-cache

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install deps
        run: yarn install

      - name: Run tests
        run: yarn test:ci

  lint:
    runs-on: ubuntu-latest
    needs: build-and-cache

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install deps
        run: yarn install

      - name: Run lint
        run: yarn lint:ci

  e2e:
    runs-on: ubuntu-latest

    needs: build-and-cache

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install deps
        run: yarn install

      - name: Run tests e2e
        run: yarn e2e
